language: node_js
node_js:
- stable
jobs:
  include:
  - stage: test
    script: npm run test
    after_success: npm run coverage
  - stage: build and deploy
    script: npm run build && npm run build_docs && ls
    deploy:
      - provider: releases
        api_key:
          secure: $GITHUB_TOKEN
        skip_cleanup: true
        skip_test: true
        file: 
          - ./dist/pyutils.mjs
          - ./dist/pyutils.node.js
        on:
          repo: fcole90/pyutils
          all_branches: true
          tags: true
      - provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        keep_history: true
        local_dir: ./docs
        on:
          repo: fcole90/pyutils
          branch: master
      # provider: npm
      # email: "fcole90@gmail.com"
      # api_key: "YOUR_AUTH_TOKEN"
